#!/bin/bash

if [[ $# -lt 2 ]]; then
    echo "Usage: asm <input.c> <output.extension>"
    exit
fi

debug=${debug:-0}

if [[ $debug == 1 ]]; then
    ./compile -c -g -Wa,-adhl $1 > $2
    echo debug
else
    ./compile -S $1 -o $2
fi