#!/bin/bash

if [[ $# -lt 2 ]]; then
    echo "Usage: asm <input.c> <output.extension>"
    exit
fi

cmd=${3:-}

ARCH="-march=armv7-a -mthumb -Wl,-Ttext=0x100 -Wa,-mthumb"
CODE="-O0 -std=gnu99 -fno-stack-protector -fno-exceptions -fno-asynchronous-unwind-tables -fPIC -e main"
NOLIB="-nostdlib -nodefaultlibs"
ACC="arm-none-eabi-gcc $ARCH $CODE $NOLIB"

if [[ "$cmd" == "debug" ]]; then
    echo asm debug
    $ACC -g -Wa,-adhl $1 > $2
elif [[ "$cmd" == "obj" ]]; then
    echo asm obj
    $ACC -nostdlib $1 -o $2
else
    $ACC -S $1 -o $2
fi