#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo "Usage: extract <input.o> "
    exit
fi

obj=$1
outText=${obj%.*}.text
outData=${obj%.*}.data

arm-none-eabi-objcopy -O binary --only-section=.data $obj $outData
arm-none-eabi-objcopy -O binary --only-section=.text $obj $outText